root: ../../data
dataset: MovieLens1M_550_Chron
maxlen: 200
num_heads: 2
num_blocks: 4
hidden_size: 64
hidden_act: gelu
hidden_dropout_prob: 0.3

epochs: 300
batch_size: 512
optimizer: adam
lr: 1.e-4
weight_decay: 1.e-6

# loss
loss: SCE
alpha: 100
num_negs: 100
neg_pool: all