dataset: AmazonBeauty_550_Chron
root: ../../data
maxlen: 50
embedding_dim: 64
dropout_rate: 0.5
num_gru_layers: 1

epochs: 300
batch_size: 512
lr: 5.e-4
weight_decay: 1.e-6

# loss
loss: SCE
alpha: 100
num_negs: 500
neg_pool: all