dataset: MovieLens1M_550_Chron
root: ../../data
maxlen: 200
embedding_dim: 64
dropout_rate: 0.3
num_gru_layers: 1

epochs: 300
batch_size: 512
lr: 1.e-3
weight_decay: 1.e-6

# loss
loss: SCE
alpha: 100
num_negs: 100
neg_pool: all