root: ../../data
dataset: AmazonBeauty_550_Chron
maxlen: 50
num_heads: 1
num_blocks: 2
hidden_size: 64
dropout_rate: 0.6

epochs: 300
batch_size: 512
optimizer: adam
lr: 5.e-4
weight_decay: 1.e-8

loss: SCE
alpha: 100
num_negs: 500
neg_pool: all