root: ../../data
dataset: MovieLens1M_550_Chron
maxlen: 200
num_heads: 1
num_blocks: 2
hidden_size: 64
dropout_rate: 0.1

epochs: 300
batch_size: 128
optimizer: adam
lr: 1.e-3
weight_decay: 1.e-6

loss: SCE
alpha: 100
num_negs: 100
neg_pool: all