root: ../../data
dataset: Yelp_550_Chron
maxlen: 50
num_heads: 4
num_blocks: 2
hidden_size: 64
dropout_rate: 0.1
mask_prob: 0.5

epochs: 300
batch_size: 256
optimizer: adam
lr: 1.e-3
weight_decay: 1.e-8

loss: SCE
alpha: 100
num_negs: 100
neg_pool: all