dataset: AmazonBeauty_550_Chron
root: ../../data
maxlen: 5
hidden_size: 64
dropout_rate: 0.7
num_vert: 4
num_horiz: 16

epochs: 300
batch_size: 512
optimizer: adam
lr: 5.e-3
weight_decay: 5.e-4

# loss
loss: SCE
alpha: 100
num_negs: 500
neg_pool: all