dataset: MovieLens1M_550_Chron
root: ../../data
maxlen: 5
hidden_size: 64
dropout_rate: 0.4
num_vert: 4
num_horiz: 16

epochs: 300
batch_size: 512
optimizer: adam
lr: 1.e-4
weight_decay: 1.e-6

# loss
loss: SCE
alpha: 100
num_negs: 100
neg_pool: all