dataset: Yelp_550_Chron
root: ../../data
maxlen: 5
hidden_size: 64
dropout_rate: 0.7
num_vert: 4
num_horiz: 16

epochs: 50
batch_size: 512
optimizer: adam
lr: 5.e-3
weight_decay: 1.e-8

# loss
loss: SCE
alpha: 100
num_negs: 100
neg_pool: all

eval_freq: 1